INSERT INTO book (author, publisher, title, year)
VALUES ('John Doe', 'publisher', 'The best book', 2001),
       ('John Doe2', 'publisher2', 'The best book2', 2002),
       ('John Doe3', 'publisher3', 'The best book3', 2003),
       ('John Doe4', 'publisher4', 'The best book4', 2004),
       ('John Doe2', 'publisher5', 'The best book5', 2005),
       ('John Doe2', 'publisher6', 'The best book6', 2006),
       ('John Doe2', 'publisher7', 'The best book7', 2007);

insert into book_copy (serial_number, book_id)
VALUES (gen_random_uuid(), 1),
       (gen_random_uuid(), 2),
       (gen_random_uuid(), 2),
       (gen_random_uuid(), 3),
       (gen_random_uuid(), 4),
       (gen_random_uuid(), 6),
       (gen_random_uuid(), 7),
       (gen_random_uuid(), 5),
       (gen_random_uuid(), 5),
       (gen_random_uuid(), 1),
       (gen_random_uuid(), 2),
       (gen_random_uuid(), 5),
       (gen_random_uuid(), 4),
       (gen_random_uuid(), 6),
       (gen_random_uuid(), 6),
       (gen_random_uuid(), 7),
       (gen_random_uuid(), 7),
       (gen_random_uuid(), 6),
       (gen_random_uuid(), 2),
       (gen_random_uuid(), 2),
       (gen_random_uuid(), 3),
       (gen_random_uuid(), 4);